### ISSUE TITLE
Consulta Git; Comando git pull  

### ISSUE THREAD

**Issue by LGilat** [LGilat/practica_dwec_gestor_presupuesto#2]
Muy Buenas;  @pedroprieto,
_Ejecuto en consola_: `git pull profesor master`
![imagen](https://user-images.githubusercontent.com/91315379/197811945-229fe496-cf81-45f1-8c67-4d6e3b2dcac2.png)
Como muestra la imagen el local está actualizado. Sin embargo entro al repo oficial y el fichero interacciónHTML existe y con texto. En local el fichero no lo tengo (bueno lo he creado a mano).  Aún así debería mostrar la diferencia, si acaso al ejecutar `git pull profesor master` .  Que no pasa nada lo copio y ya está pero quiero saber qué es lo que no entiendo. 

Saludos, Luis Gilabert

**Comment by pedroprieto** [comment]
Buenas,

Está correcto, no te preocupes. Lo que pasa es que no hay cambios en mi rama con respecto a la tuya.

Debes tener dos remotos: el mío y el tuyo (en tu repositorio propio de GitHub, el fork).

Ambos están sincronizados en un punto. A partir de ahí, tú has ido haciendo cambios (commits en local) a continuación de dicho punto. Por eso, cuando haces un `git pull` del mío, no encuentra nada, porque el mío está en un estado anterior y no he publicado nada nuevo.

Sin embargo, si haces un `git push` a tu repositorio de GitHub, subirás los cambios locales a tu repositorio.

Espero habértelo aclarado. Un saludo!!

**Comment by LGilat** [comment]
Sí, sí. De acuerdo. 
Estaba entendiéndolo mal. Daba por hecho que si hay diferencia al hacer pull actualiza. Claro, y el remoto no tiene porque saber lo que yo tengo en local. 
Y como dices;  al estar varios commits por delante no me va a restaurar a un punto anterior.  
Estaba convencidísimo. 
Perfecto, muchas gracias. 
Saludos! Cierro el Issue
